# Generated by Django 4.2.5 on 2023-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_folder_weddingimage_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_image',
            field=models.ImageField(blank=True, null=True, upload_to='folder_images/'),
        ),
    ]
